INSERT INTO ROLE (LIBELLE) VALUES ("Utilisateur");
INSERT INTO ROLE (LIBELLE) VALUES ("Candidat");
INSERT INTO ROLE (LIBELLE) VALUES ("Manager");
INSERT INTO ROLE (LIBELLE) VALUES ("Administrateur");
